### ISSUE TITLE
Anti Spam Chat Delay 1 second = 2 seconds

### ISSUE THREAD

**Issue by Ajneb97** [Crazy-Crew/ChatManager#98]
### Plugin Version

4.0.3

### Server Version

1.21.4

### Server Platform

Paper

### Describe the bug

The Chat Delay on the Anti Spam section for some reason is adding 1 additional second to the real value. If I set a 1 second chat delay, in fact it is a 2 seconds delay.

```
Anti_Spam:
  # Anti-spam section for chat.
  Chat:
    # How many seconds does the player have to wait till they send their next message?
    # Set to 0 to disable.
    Chat_Delay: 1
    # Prevent players from repeating the same messages.
    Block_Repetitive_Messages: false
```

![Image](https://github.com/user-attachments/assets/5854312d-e382-433b-99f6-e6b13fd5effe)

### Steps to reproduce

1. Set Chat Delay to 1
2. Start writing on the chat, the delay is 2 seconds and not 1.

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [x] My version of Minecraft is supported by CrazyCrew.
